version: "3.7"
services:
        service1:
                image: callumgoodley/service1
                build: ./service1
                environment:
                          DB_USERNAME: ${DB_USERNAME}
                          DB_PASSWORD: ${DB_PASSWORD} 
                          MY_SECRET_KEY: ${MY_SECRET_KEY}
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - service2
                        - service3
                        - service4
                        - mysql

        service2:
                image: callumgoodley/service2
                build: ./service2
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
        service3: 
                image: callumgoodley/service3
                build: ./service3
                ports: 
                        - target: 5002
                          published: 5002
                          protocol: tcp
        service4:
                image: callumgoodley/service4
                build: ./service4
                ports:
                        - target: 5003
                          published: 5003
                          protocol: tcp
        nginx:
                image: nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp

                depends_on: 
                        - service1
                volumes: 
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
        mysql:
               image: callumgoodley/rapper_name_mysql
               build: ./db 
               environment:
                          MYSQL_USER: ${DB_USERNAME}
                          MYSQL_PASSWORD: ${DB_PASSWORD}
                          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                          MYSQL_DATABASE: rapper-name-db
               ports:
                       - target: 3306
                         published: 3306
                         protocol: tcp
        mysql_test:
                    image: callumgoodley/test_db
                    build: ./testdb
                    environment:
                               MYSQL_USER: ${DB_USERNAME}
                               MYSQL_PASSWORD: ${DB_PASSWORD}
                               MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                               MYSQL_DATABASE: test
                    ports:
                            - target: 3307
                              published: 3307
                              protocol: tcp
