pipeline {
    agent any 
    environment {
        MY_SECRET_KEY='aeiou'
        DB_USERNAME='callumgoodley'
        DB_PASSWORD='root'
    }
    stages {
        stage('Build - docker') { 
            steps {
                sh "bash /home/jenkins/.jenkins/workspace/rap-name-generator/jenkins/build.sh"
            }
        }
        stage('Test - pytest') { 
            steps {
                sh "bash /home/jenkins/.jenkins/workspace/rap-name-generator/jenkins/testing.sh"
            }
        }
        stage('Configure and Deploy - Ansible') { 
            steps {
                sh "bash /home/jenkins/.jenkins/workspace/rap-name-generator/jenkins/config-deploy.sh"
            }
        }
    }
}
