pipeline {
    agent any 
    stages {
        stage('Build - docker') {  
            steps {
                sh "bash ./jenkins/build.sh"
            }
        }
        stage('Test - pytest') { 
            steps {
                sh "bash ./jenkins/testing.sh"
            }
        }
        stage('Configure and Deploy - Ansible') { 
            steps {
                sh "bash ./jenkins/config-deploy.sh"
            }
        }
    }
    post {
        always {
          step([$class: 'Mailer',
            notifyEveryUnstableBuild: true,
            recipients: "callumgoodley@googlemail.com",
            sendToIndividuals: true])
        }
    }
}
