pipeline {
    agent any 
    environment {
        MY_SECRET_KEY='aeiou'
        DB_USERNAME='callumgoodley'
        DB_PASSWORD='root'
    }
    stages {
        stage('Build - docker') { 
            steps {
                sh "bash ./jenkins/build.sh"
            }
        }
        stage('Test - pytest') { 
            steps {
                sh "bash ./jenkins/testing.sh"
            }
        }
        stage('Configure and Deploy - Ansible') { 
            steps {
                sh "bash ./jenkins/config-deploy.sh"
            }
        }
    }
    post {
        always {
            emailext body: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS: Check console output at $BUILD_URL to view the results.', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!'
        }
    }
}
