---
- hosts: all
  become: true
  roles:
  - common

- hosts: managers
  become: true
  roles:
  - role: manager

- hosts: workers
  become: true
  roles:
  - role: worker

- hosts: managers
  become: true
  roles:
  - role:  deploy-stack
