- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: rapstack
    compose:
            - /home/callumgoodley/rap_name_generator/docker-compose.yaml
  environment:
          MY_SECRET_KEY: aeiou
          DB_USERNAME: callumgoodley
          DB_PASSWORD: root

ssh callumgoodley@rap-manager << EOF
sudo docker service update -–replicas 3 rapstack_service1
sudo docker service update -–replicas 3 rapstack_service2
sudo docker service update -–replicas 3 rapstack_service3
sudo docker service update -–replicas 3 rapstack_service4
sudo docker service update --replicas 3 rapstack_mysql
